name: quickbuild
services:
  quickbuild:
    container_name: quickbuild-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8810:8810"
    volumes:
      - quickbuild:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config/hibernate.properties:/quickbuild/conf/hibernate.properties
    # environment:
    #   - QUICKBUILD_DB_TYPE=postgres
    #   - QUICKBUILD_DB_HOST=postgres:5432
    #   - QUICKBUILD_DB_NAME=quickbuild
    #   - QUICKBUILD_DB_USER=quickbuild
    #   - QUICKBUILD_DB_PASSWD=supersecret
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: quickbuild-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=quickbuild
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=quickbuild
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
  quickbuild: